version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directory: /service
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
