services:
  zpanel:
    image: 'vivalucas/zpanel:latest'
    container_name: zpanel
    volumes:
      - ./conf:/app/conf
      - ./uploads:/app/uploads
      - ./database:/app/database
    # - ./runtime:/app/runtime
    ports:
      - 6521:6521
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://127.0.0.1:6521/api/healthz']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
